class WebsiteData {
  String name;
  String url;
  List<String> category;
  List<String> tags;
  String description;
  String image;
  bool isFavorite;

  WebsiteData({
    required this.name,
    required this.url,
    required this.category,
    required this.tags,
    required this.description,
    required this.image,
    required this.isFavorite,
  });
}

var popularWebsites = [
  WebsiteData(
    name: "Google",
    url: "https://www.google.com",
    category: ["Search Engine"],
    tags: ["Search", "Web", "Images", "Maps"],
    description: "The world's most popular search engine.",
    image: "https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png",
    isFavorite: true,
  ),
  WebsiteData(
    name: "YouTube",
    url: "https://www.youtube.com",
    category: ["Video Sharing"],
    tags: ["Videos", "Music", "Channels", "Live"],
    description: "The world's most popular video sharing platform.",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png",
    isFavorite: false,
  ),
  WebsiteData(
    name: "Facebook",
    url: "https://www.facebook.com",
    category: ["Social Media"],
    tags: ["Friends", "Family", "Connect"],
    description: "Connect with friends and the world around you on Facebook.",
    image: "https://www.facebook.com/images/fb_icon_325x325.png",
    isFavorite: true,
  ),
  WebsiteData(
    name: "Twitter",
    url: "https://twitter.com",
    category: ["Social Media"],
    tags: ["Tweets", "Follow", "News"],
    description: "Join the conversation! Twitter is your go-to social media app.",
    image: "https://abs.twimg.com/responsive-web/client-web/icon-ios.b1fc7275.png",
    isFavorite: false,
  ),
  WebsiteData(
    name: "Amazon",
    url: "https://www.amazon.com",
    category: ["Online Shopping"],
    tags: ["Shop", "Books", "Electronics"],
    description: "Shop online for electronics, apparel, books, and more on Amazon.",
    image: "https://companieslogo.com/img/orig/AMZN-e9f942e4.png?t=1632523695",
    isFavorite: true,
  ),
  WebsiteData(
    name: "GitHub",
    url: "https://github.com",
    category: ["Software Development"],
    tags: ["Code", "Collaborate", "Open Source"],
    description: "GitHub is where over 65 million developers shape the future of software.",
    image: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
    isFavorite: true,
  ),
WebsiteData(
name: "Netflix",
url: "https://www.netflix.com/",
category: ["Streaming Services"],
tags: ["Movies", "TV Shows", "Documentaries"],
description: "Watch TV shows and movies online.",
image: "https://www.freepnglogos.com/uploads/netflix-logo-circle-png-5.png",
isFavorite: true,
),
WebsiteData(
name: "Instagram",
url: "https://www.instagram.com/",
category: ["Social Media"],
tags: ["Photos", "Videos", "Stories"],
description: "Bringing you closer to the people and things you love.",
image: "https://download.logo.wine/logo/Instagram/Instagram-Logo.wine.png",
isFavorite: true,
),
WebsiteData(
name: "LinkedIn",
url: "https://www.linkedin.com/",
category: ["Professional Networking"],
tags: ["Jobs", "Networking", "Professional Development"],
description: "A social networking platform for professionals.",
image: "https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-linkedin-512.png",
isFavorite: false,
),
WebsiteData(
name: "Reddit",
url: "https://www.reddit.com/",
category: ["Social News and Discussion"],
tags: ["News", "Discussion", "Community"],
description: "The front page of the internet.",
image: "https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-57x57.png",
isFavorite: true,
),
WebsiteData(
name: "Etsy",
url: "https://www.etsy.com/",
category: ["Online Marketplace"],
tags: ["Handmade", "Vintage", "Crafts"],
description: "A global marketplace for unique and creative goods.",
image: "https://1000logos.net/wp-content/uploads/2017/12/Etsy-emblem.jpg",
isFavorite: false,
),
WebsiteData(
name: "Wikipedia",
url: "https://www.wikipedia.org/",
category: ["Online Encyclopedia"],
tags: ["Information", "Research", "Knowledge"],
description: "A free online encyclopedia.",
image: "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1280px-Wikipedia-logo-v2.svg.png",
isFavorite: true,
),
WebsiteData(
name: "Pinterest",
url: "https://www.pinterest.com/",
category: ["Social Media"],
tags: ["Ideas", "Inspiration", "DIY"],
description: "Discover recipes, home ideas, style inspiration and other ideas to try.",
image: "https://upload.wikimedia.org/wikipedia/commons/0/08/Pinterest-logo.png",
isFavorite: false,
),
WebsiteData(
name: "Twitch",
url: "https://www.twitch.tv/",
category: ["Live Streaming"],
tags: ["Gaming", "Esports", "Live Streams"],
description: "A live streaming platform for gamers.",
image: "https://www.freepnglogos.com/uploads/purple-twitch-logo-png-18.png",
isFavorite: false,
),
WebsiteData(
name: "Zoom",
url: "https://www.zoom.us/",
category: ["Video Conferencing"],
tags: ["Meetings", "Webinars", "Video Calls"],
description: "Video conferencing, online meetings, and webinars made easy.",
image: "https://www.freepnglogos.com/uploads/zoom-logo-png/zoom-meeting-logo-transparent-png-21.png",
  isFavorite: true,
),
  WebsiteData(
    name: "Medium",
    url: "https://medium.com/",
    category: ["Blogging"],
    tags: ["Writing", "Stories", "Read"],
    description: "A place to read, write, and interact with the stories that matter most to you.",
    image: "https://www.iconpacks.net/icons/2/free-medium-icon-2177-thumb.png",
    isFavorite: true,
  ),
  WebsiteData(
    name: "Slack",
    url: "https://slack.com/",
    category: ["Team Collaboration"],
    tags: ["Messaging", "Collaboration", "Team"],
    description: "Where work happens.",
    image: "https://cdn-icons-png.flaticon.com/512/732/732245.png",
    isFavorite: false,
  ),

  WebsiteData(
    name: "Airbnb",
    url: "https://www.airbnb.com/",
    category: ["Vacation Rentals"],
    tags: ["Travel", "Stay", "Homes"],
    description: "Vacation rentals, homes, experiences & places - Airbnb.",
    image: "https://cdn-icons-png.flaticon.com/512/2111/2111320.png",
    isFavorite: false,
  ),
  WebsiteData(
    name: "Dropbox",
    url: "https://www.dropbox.com/",
    category: ["Cloud Storage"],
    tags: ["Files", "Collaboration", "Cloud"],
    description: "Keep your files safe and secure in the cloud.",
    image: "https://cdn-icons-png.flaticon.com/512/4138/4138137.png",
    isFavorite: true,
  ),
  WebsiteData(
    name: "Coursera",
    url: "https://www.coursera.org/",
    category: ["Online Learning"],
    tags: ["Education", "Online Courses", "Certificates"],
    description: "Take online courses from the world's top universities and companies.",
    image: "https://d3njjcbhbojbot.cloudfront.net/web/images/favicons/apple-touch-icon-144x144.png",
    isFavorite: false,
  ),
  WebsiteData(
    name: "Google Drive",
    url: "https://www.google.com/drive/",
    category: ["Cloud Storage"],
    tags: ["Files", "Collaboration", "Cloud"],
    description: "Keep everything. Share anything.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Google_Drive_icon_%282020%29.svg/1147px-Google_Drive_icon_%282020%29.svg.png",
    isFavorite: true,
  ),
  WebsiteData(
    name: "Canva",
    url: "https://www.canva.com/",
    category: ["Graphic Design"],
    tags: ["Design", "Templates", "Graphics"],
    description: "Create beautiful designs with Canva.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Canva_icon_2021.svg/2048px-Canva_icon_2021.svg.png",
    isFavorite: true,
  ),

// Add more websites here...
];
